"""
api/ — admin JSON API handlers split by domain.

Re-exports every public *_api function so main.py can keep importing
from Backend.fastapi.routes.api_routes (shim) or from this package.
"""

from Backend.fastapi.routes.api.bot_admin import (
    bot_admin_apply_api,
    bot_admin_apply_status_api,
    bot_admin_scan_api,
)

from Backend.fastapi.routes.api.catalogs import (
    add_custom_catalog_item_api,
    auto_catalog_sync_status_api,
    auto_sync_custom_catalogs_api,
    create_custom_catalog_api,
    delete_custom_catalog_api,
    get_auto_catalog_settings_api,
    get_catalog_order_api,
    get_custom_catalog_items_api,
    list_custom_catalogs_api,
    remove_custom_catalog_item_api,
    update_auto_catalog_settings_api,
    update_catalog_order_api,
    update_custom_catalog_api,
)

from Backend.fastapi.routes.api.media import (
    apply_media_rescan_api,
    delete_media_api,
    delete_movie_quality_api,
    delete_tv_episode_api,
    delete_tv_quality_api,
    delete_tv_season_api,
    get_media_details_api,
    get_media_visibility_api,
    list_manual_add_catalogs_api,
    list_media_api,
    manual_add_media_api,
    resolve_manual_metadata_api,
    resolve_telegram_api,
    search_catalog_media_api,
    search_media_rescan_api,
    set_media_visibility_api,
    update_media_api,
)

from Backend.fastapi.routes.api.requests import (
    delete_request_api,
    get_requests_api,
    request_popular_api,
    request_search_api,
    request_submit_api,
    update_request_api,
)

from Backend.fastapi.routes.api.session import (
    session_disconnect_api,
    session_reconnect_api,
    session_remove_api,
    session_send_code_api,
    session_status_api,
    session_verify_code_api,
    session_verify_password_api,
)

from Backend.fastapi.routes.api.settings import (
    get_settings_api,
    update_settings_api,
)

from Backend.fastapi.routes.api.speed_test import (
    speed_test_api,
    speed_test_stream_api,
)

from Backend.fastapi.routes.api.subscription import (
    add_subscription_plan_api,
    assign_plan_api,
    backfill_subscriber_names_api,
    delete_subscription_plan_api,
    get_all_subscribers_api,
    get_subscription_plans_api,
    manage_subscriber_api,
    subscription_preflight_api,
    update_subscription_plan_api,
)

from Backend.fastapi.routes.api.subtitles_api import (
    add_subtitles_api,
    list_subtitle_languages_api,
    list_subtitles_api,
    remove_subtitle_api,
    resolve_subtitle_api,
)

from Backend.fastapi.routes.api.system import (
    clear_cache_api,
    clear_stream_analytics_api,
    download_logs_api,
    export_config_api,
    get_admin_stats_api,
    get_db_stats_api,
    get_logs_api,
    get_stream_analytics_api,
    get_system_stats_api,
    get_user_activity_api,
    health_api,
    health_report_api,
    import_config_api,
    restart_app_api,
    setup_status_api,
    version_status_api,
)

from Backend.fastapi.routes.api.tokens import (
    create_token_api,
    get_all_tokens_api,
    grant_lifetime_api,
    link_token_user_api,
    revoke_token_api,
    set_token_expiry_api,
    set_token_lifetime_api,
    update_token_limits_api,
)

from Backend.fastapi.routes.api.tools import (
    cancel_dbcheck_api,
    cancel_duplicate_check_api,
    cancel_scan_api,
    clear_manual_session_api,
    dbcheck_status_api,
    duplicate_check_status_api,
    get_dead_links_api,
    get_manual_session_api,
    get_tools_channels_api,
    purge_dead_links_api,
    purge_duplicates_api,
    scan_status_api,
    search_manual_session_api,
    set_manual_session_api,
    start_dbcheck_api,
    start_duplicate_check_api,
    start_scan_api,
)

__all__ = [
    "add_custom_catalog_item_api",
    "add_subscription_plan_api",
    "add_subtitles_api",
    "apply_media_rescan_api",
    "assign_plan_api",
    "auto_catalog_sync_status_api",
    "auto_sync_custom_catalogs_api",
    "backfill_subscriber_names_api",
    "bot_admin_apply_api",
    "bot_admin_apply_status_api",
    "bot_admin_scan_api",
    "cancel_dbcheck_api",
    "cancel_duplicate_check_api",
    "cancel_scan_api",
    "clear_cache_api",
    "clear_manual_session_api",
    "clear_stream_analytics_api",
    "create_custom_catalog_api",
    "create_token_api",
    "dbcheck_status_api",
    "delete_custom_catalog_api",
    "delete_media_api",
    "delete_movie_quality_api",
    "delete_request_api",
    "delete_subscription_plan_api",
    "delete_tv_episode_api",
    "delete_tv_quality_api",
    "delete_tv_season_api",
    "download_logs_api",
    "duplicate_check_status_api",
    "export_config_api",
    "get_admin_stats_api",
    "get_all_subscribers_api",
    "get_all_tokens_api",
    "get_auto_catalog_settings_api",
    "get_catalog_order_api",
    "get_custom_catalog_items_api",
    "get_db_stats_api",
    "get_dead_links_api",
    "get_logs_api",
    "get_manual_session_api",
    "get_media_details_api",
    "get_media_visibility_api",
    "get_requests_api",
    "get_settings_api",
    "get_stream_analytics_api",
    "get_subscription_plans_api",
    "get_system_stats_api",
    "get_tools_channels_api",
    "get_user_activity_api",
    "grant_lifetime_api",
    "health_api",
    "health_report_api",
    "import_config_api",
    "link_token_user_api",
    "list_custom_catalogs_api",
    "list_manual_add_catalogs_api",
    "list_media_api",
    "list_subtitle_languages_api",
    "list_subtitles_api",
    "manage_subscriber_api",
    "manual_add_media_api",
    "purge_dead_links_api",
    "purge_duplicates_api",
    "remove_custom_catalog_item_api",
    "remove_subtitle_api",
    "request_popular_api",
    "request_search_api",
    "request_submit_api",
    "resolve_manual_metadata_api",
    "resolve_subtitle_api",
    "resolve_telegram_api",
    "restart_app_api",
    "revoke_token_api",
    "scan_status_api",
    "search_catalog_media_api",
    "search_manual_session_api",
    "search_media_rescan_api",
    "session_disconnect_api",
    "session_reconnect_api",
    "session_remove_api",
    "session_send_code_api",
    "session_status_api",
    "session_verify_code_api",
    "session_verify_password_api",
    "set_manual_session_api",
    "set_media_visibility_api",
    "set_token_expiry_api",
    "set_token_lifetime_api",
    "setup_status_api",
    "speed_test_api",
    "speed_test_stream_api",
    "start_dbcheck_api",
    "start_duplicate_check_api",
    "start_scan_api",
    "subscription_preflight_api",
    "update_auto_catalog_settings_api",
    "update_catalog_order_api",
    "update_custom_catalog_api",
    "update_media_api",
    "update_request_api",
    "update_settings_api",
    "update_subscription_plan_api",
    "update_token_limits_api",
    "version_status_api",
]
